FROM node:18-alpine

ARG NODE_AUTH_TOKEN

RUN mkdir -p /usr/src/binant-codetest-events && chown -R node:node /usr/src/binant-codetest-events
RUN mkdir -p /usr/src/shared && chown -R node:node /usr/src/shared

WORKDIR /usr/src/binant-codetest-events

USER node

COPY --chown=node:node ./events/package.json ./events/yarn.lock ./

RUN yarn install

COPY --chown=node:node ./events/src src

CMD ["npm", "run", "dev"]
